package com.bloomteen.pcosassessor.ui.theme

import androidx.compose.ui.graphics.Color

// Core Brand Palette (from DESIGN.md & code.html)
val Primary = Color(0xFF624F93)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFF7B68AE)
val OnPrimaryContainer = Color(0xFFFEF8FF)
val PrimaryFixed = Color(0xFFEDE3FF)
val PrimaryFixedDim = Color(0xFFCFBCFF)
val OnPrimaryFixed = Color(0xFF210A50)
val OnPrimaryFixedVariant = Color(0xFF4D3B7E)

// Secondary (Sage Mint)
val Secondary = Color(0xFF2E6B5A)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFB8EEDA)
val OnSecondaryContainer = Color(0xFF265446)
val SecondaryFixed = Color(0xFFB8EEDA)
val SecondaryFixedDim = Color(0xFF9CD1BE)
val OnSecondaryFixed = Color(0xFF002018)
val OnSecondaryFixedVariant = Color(0xFF13473B)

// Tertiary (Dusty Rose / High Risk)
val Tertiary = Color(0xFFA24B5D)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFFA35F6D)
val OnTertiaryContainer = Color(0xFFFFF8F8)
val TertiaryFixed = Color(0xFFFFE0E4)
val TertiaryFixedDim = Color(0xFFFFB2BF)
val OnTertiaryFixed = Color(0xFF40111E)
val OnTertiaryFixedVariant = Color(0xFF6F3441)

// Surfaces & Background
val Background = Color(0xFFFBF7FF)
val OnBackground = Color(0xFF1F1926)
val Surface = Color(0xFFFBF7FF)
val SurfaceDim = Color(0xFFE1D6E9)
val SurfaceBright = Color(0xFFFEF7FF)
val SurfaceContainerLowest = Color(0xFFFFFFFF)
val SurfaceContainerLow = Color(0xFFFAF0FF)
val SurfaceContainer = Color(0xFFF5EAFD)
val SurfaceContainerHigh = Color(0xFFF0E6F9)
val SurfaceContainerHighest = Color(0xFFE9DFF2)
val OnSurface = Color(0xFF201A27)
val OnSurfaceVariant = Color(0xFF595363)
val Outline = Color(0xFF7A7581)
val OutlineVariant = Color(0xFFE5DEEE)

// Clinical Risk & Status System (DESIGN.md section 156-161 & code.html)
val RiskHighText = Color(0xFFA24B5D)
val RiskHighBg = Color(0xFFFFF1F2)
val RiskHighBorder = Color(0xFFFECDD3)
val RiskHighDot = Color(0xFFC44053)

val RiskModerateText = Color(0xFF624F93)
val RiskModerateBg = Color(0xFFFAF5FF)
val RiskModerateBorder = Color(0xFFDDD6FE)
val RiskModerateDot = Color(0xFF7B68AE)

val RiskLowText = Color(0xFF2E6B5A)
val RiskLowBg = Color(0xFFECFDF5)
val RiskLowBorder = Color(0xFFA7F3D0)
val RiskLowDot = Color(0xFF3B7A57)
